version: '3.8'
services:
  frontend:
    build:
      context: ./supplychain-Internship-main
      dockerfile: Dockerfile
    volumes:
      - ./supplychain-Internship-main:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  contracts:
    build:
      context: ./solidity-supplychain
      dockerfile: Dockerfile
    volumes:
      - ./solidity-supplychain:/usr/src/app:cached
    command: ["npx", "hardhat", "node"]
